<?php return array(
    'root' => array(
        'name' => 'ithemes/ithemes-security-pro',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => 'ec7b336cfe274a00048c5c927352951d59b27b79',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'beberlei/assert' => array(
            'pretty_version' => 'v3.3.2',
            'version' => '3.3.2.0',
            'reference' => 'cb70015c04be1baee6f5f5c953703347c0ac1655',
            'type' => 'library',
            'install_path' => __DIR__ . '/../beberlei/assert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bjeavons/zxcvbn-php' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => '994928ae5b17ecff8baa2406832d37bdf01116c0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bjeavons/zxcvbn-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'brick/math' => array(
            'pretty_version' => '0.9.3',
            'version' => '0.9.3.0',
            'reference' => 'ca57d18f028f84f777b2168cd1911b0dee2343ae',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'deliciousbrains/wp-background-processing' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => 'ebbed762c42e70e76573ffbd36e591378ba5f2ee',
            'type' => 'library',
            'install_path' => __DIR__ . '/../deliciousbrains/wp-background-processing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'fgrosse/phpasn1' => array(
            'pretty_version' => 'v2.5.0',
            'version' => '2.5.0.0',
            'reference' => '42060ed45344789fb9f21f9f1864fc47b9e3507b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fgrosse/phpasn1',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ithemes/ithemes-security-pro' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'ec7b336cfe274a00048c5c927352951d59b27b79',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/constant_time_encoding' => array(
            'pretty_version' => 'v2.6.3',
            'version' => '2.6.3.0',
            'reference' => '58c3f47f650c94ec05a151692652a868995d2938',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/constant_time_encoding',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'patchstack/firewall' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '525fe1adb710daf67c36789a076d5f8fcef01bd0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../patchstack/firewall',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'pimple/pimple' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => 'a94b3a4db7fb774b3d78dad2315ddc07629e1bed',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pimple/pimple',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '2ae37329ee82f91efadc282cc2d527fd6065a5ef',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spomky-labs/cbor-php' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'reference' => '28e2712cfc0b48fae661a48ffc6896d7abe83684',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spomky-labs/cbor-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'stellarwp/container-contract' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => 'b2c42c76681db314e4edbb2af0a312b6c06b495e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stellarwp/container-contract',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'stellarwp/telemetry' => array(
            'pretty_version' => '2.3.2',
            'version' => '2.3.2.0',
            'reference' => 'a4bc84f1b9539ae5418e76caab31355191273a9c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stellarwp/telemetry',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.28.0',
            'version' => '1.28.0.0',
            'reference' => '42292d99c55abe617799667f454222c54c60e229',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-uuid' => array(
            'pretty_version' => 'v1.28.0',
            'version' => '1.28.0.0',
            'reference' => '9c44518a5aff8da565c8a55dbe85d2769e6f630e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-uuid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'web-auth/cose-lib' => array(
            'pretty_version' => 'v3.3.12',
            'version' => '3.3.12.0',
            'reference' => 'efa6ec2ba4e840bc1316a493973c9916028afeeb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../web-auth/cose-lib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
