<?php
namespace WP_Media_Folder\Aws\Sms;

use WP_Media_Folder\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS Server Migration Service** service.
 * @method \WP_Media_Folder\Aws\Result createApp(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise createAppAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result createReplicationJob(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise createReplicationJobAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result deleteApp(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise deleteAppAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result deleteAppLaunchConfiguration(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise deleteAppLaunchConfigurationAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result deleteAppReplicationConfiguration(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise deleteAppReplicationConfigurationAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result deleteReplicationJob(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise deleteReplicationJobAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result deleteServerCatalog(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise deleteServerCatalogAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result disassociateConnector(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise disassociateConnectorAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result generateChangeSet(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise generateChangeSetAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result generateTemplate(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise generateTemplateAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result getApp(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise getAppAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result getAppLaunchConfiguration(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise getAppLaunchConfigurationAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result getAppReplicationConfiguration(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise getAppReplicationConfigurationAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result getConnectors(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise getConnectorsAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result getReplicationJobs(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise getReplicationJobsAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result getReplicationRuns(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise getReplicationRunsAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result getServers(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise getServersAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result importServerCatalog(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise importServerCatalogAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result launchApp(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise launchAppAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result listApps(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise listAppsAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result putAppLaunchConfiguration(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise putAppLaunchConfigurationAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result putAppReplicationConfiguration(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise putAppReplicationConfigurationAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result startAppReplication(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise startAppReplicationAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result startOnDemandReplicationRun(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise startOnDemandReplicationRunAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result stopAppReplication(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise stopAppReplicationAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result terminateApp(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise terminateAppAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result updateApp(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise updateAppAsync(array $args = [])
 * @method \WP_Media_Folder\Aws\Result updateReplicationJob(array $args = [])
 * @method \WP_Media_Folder\GuzzleHttp\Promise\Promise updateReplicationJobAsync(array $args = [])
 */
class SmsClient extends AwsClient {}
